#!/usr/bin/env bash
# =============================================================================
# generate-clarification-report.sh - 澄清报告生成
# =============================================================================
# Purpose: 基于会话数据生成 Markdown 报告
# Usage: generate-clarification-report.sh --session .session.json --output clarifications/
# Output: Markdown file (clarifications/[timestamp]-flow-clarify.md)
# Exit codes: 0=success, 1=invalid session, 2=fatal
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

# Configuration
SESSION_FILE=""
OUTPUT_DIR=""

# =============================================================================
# T046: 报告模板定义
# =============================================================================
generate_report_template() {
    local session_data="$1"

    local session_id req_id status created_at
    session_id=$(echo "$session_data" | jq -r '.sessionId // "unknown"')
    req_id=$(echo "$session_data" | jq -r '.reqId // "REQ-XXX"')
    status=$(echo "$session_data" | jq -r '.status // "unknown"')
    created_at=$(echo "$session_data" | jq -r '.createdAt // ""')

    local questions_count questions_answered
    questions_count=$(echo "$session_data" | jq '.questions | length')
    questions_answered=$(echo "$session_data" | jq '[.questions[] | select(.answer != null)] | length')

    # 计算扫描时间
    local scan_duration_ms
    scan_duration_ms=$(echo "$session_data" | jq -r '.scanResults.scanDurationMs // 0')
    local scan_duration_sec=$((scan_duration_ms / 1000))

    cat << EOF
# Clarification Report: ${req_id}

**Session ID**: ${session_id}
**Status**: ${status}
**Created**: ${created_at}
**Duration**: ${scan_duration_sec}s (scan) + interactive Q&A

---

## Metadata

| Field | Value |
|-------|-------|
| Requirement | ${req_id} |
| Session ID | ${session_id} |
| Questions | ${questions_answered} / ${questions_count} |
| Generated | $(get_beijing_time_iso) |

---

## Scan Summary

EOF

    # 生成维度扫描摘要表格
    echo "| Dimension | Status | Issues | High Priority |"
    echo "|-----------|--------|--------|---------------|"

    echo "$session_data" | jq -r '
        .scanResults.dimensions // [] |
        .[] |
        "| \(.name) | \(.status) | \(.issues | length) | \([.issues[] | select(.priority >= 50)] | length) |"
    '

    cat << EOF

---

## Clarification Session

EOF

    # 生成每个问题的详细信息
    local idx=0
    while IFS= read -r question; do
        idx=$((idx + 1))
        local qid text answer rationale dim_id recommended
        qid=$(echo "$question" | jq -r '.questionId')
        text=$(echo "$question" | jq -r '.text')
        answer=$(echo "$question" | jq -r '.answer // "Not answered"')
        rationale=$(echo "$question" | jq -r '.rationale // "N/A"')
        dim_id=$(echo "$question" | jq -r '.dimensionId')
        recommended=$(echo "$question" | jq -r '.recommendedOption // "N/A"')

        cat << EOF
### ${qid}: Question ${idx}

**Question**: ${text}

**Dimension**: ${dim_id}

**Options**:
EOF
        echo "$question" | jq -r '.options // [] | .[] | "- **\(.optionId)**: \(.text) - \(.description // "")"'

        cat << EOF

**AI Recommended**: ${recommended} ⭐

**User Answer**: ${answer}

**Rationale**: ${rationale}

---

EOF
    done < <(echo "$session_data" | jq -c '.questions // [] | .[]')

    cat << EOF
## Coverage Summary

| Aspect | Status |
|--------|--------|
| Dimensions Scanned | 11 |
| Issues Found | $(echo "$session_data" | jq '[.scanResults.dimensions // [] | .[].issues | length] | add // 0') |
| Questions Generated | ${questions_count} |
| Questions Answered | ${questions_answered} |

---

## Next Command

EOF

    if [[ "$questions_answered" -eq "$questions_count" ]] && [[ "$questions_count" -gt 0 ]]; then
        echo "✅ Clarification complete. Run \`/flow-prd\` to generate PRD."
    elif [[ "$questions_count" -eq 0 ]]; then
        echo "✅ No ambiguities found. Run \`/flow-prd\` to generate PRD."
    else
        echo "⚠️ Clarification incomplete. Run \`/flow-clarify ${req_id}\` to continue."
    fi

    cat << EOF

---

**Generated by**: clarify-analyst agent
**Report Version**: 1.0.0
**Template**: CC-DevFlow Clarification Report
EOF
}

# =============================================================================
# T047: 模板渲染
# =============================================================================
render_report() {
    local session_file="$1"

    # 读取会话数据
    if [[ ! -f "$session_file" ]]; then
        echo "Error: Session file not found: $session_file" >&2
        return 1
    fi

    local session_data
    session_data=$(cat "$session_file")

    # 验证 JSON
    if ! echo "$session_data" | jq -e '.' >/dev/null 2>&1; then
        echo "Error: Invalid JSON in session file" >&2
        return 1
    fi

    # 生成报告
    generate_report_template "$session_data"
}

# =============================================================================
# T048: 报告写入
# =============================================================================
write_report() {
    local content="$1"
    local output_dir="$2"
    local session_id="$3"

    # 确保输出目录存在
    mkdir -p "$output_dir"

    # 生成文件名
    local timestamp
    timestamp=$(TZ='Asia/Shanghai' date '+%Y%m%d-%H%M%S')
    local filename="${timestamp}-flow-clarify.md"
    local filepath="${output_dir}/${filename}"

    # 写入文件
    echo "$content" > "$filepath"

    # 验证写入
    if [[ -f "$filepath" ]]; then
        echo "$filepath"
        return 0
    else
        echo "Error: Failed to write report" >&2
        return 1
    fi
}

# =============================================================================
# T049: 主入口
# =============================================================================
parse_args() {
    local session_file=""
    local output_dir=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --session)
                session_file="$2"
                shift 2
                ;;
            --output)
                output_dir="$2"
                shift 2
                ;;
            --help|-h)
                echo "Usage: generate-clarification-report.sh --session .session.json [--output clarifications/]"
                exit 0
                ;;
            *)
                shift
                ;;
        esac
    done

    echo "$session_file|$output_dir"
}

main() {
    # 解析参数
    local parsed
    parsed=$(parse_args "$@")
    local session_file output_dir
    IFS='|' read -r session_file output_dir <<< "$parsed"

    # 验证输入
    if [[ -z "$session_file" ]]; then
        echo '{"error": {"code": "MISSING_SESSION", "message": "--session is required"}}' >&2
        exit 2
    fi

    if [[ ! -f "$session_file" ]]; then
        echo '{"error": {"code": "SESSION_NOT_FOUND", "message": "Session file not found"}}' >&2
        exit 1
    fi

    # 确定输出目录
    if [[ -z "$output_dir" ]]; then
        # 从会话文件路径推断
        output_dir=$(dirname "$session_file")
    fi

    # 读取会话 ID
    local session_id
    session_id=$(jq -r '.sessionId // "unknown"' "$session_file")

    # 渲染报告
    local report_content
    report_content=$(render_report "$session_file")

    if [[ -z "$report_content" ]]; then
        echo '{"error": {"code": "RENDER_FAILED", "message": "Failed to render report"}}' >&2
        exit 2
    fi

    # 写入报告
    local report_path
    report_path=$(write_report "$report_content" "$output_dir" "$session_id")

    if [[ -n "$report_path" ]]; then
        echo "{\"success\": true, \"reportPath\": \"$report_path\"}"
    else
        echo '{"error": {"code": "WRITE_FAILED", "message": "Failed to write report"}}' >&2
        exit 2
    fi
}

# 只在直接执行时运行 main
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
