# =============================================================================
# CC-DevFlow Workflow Schema v6.0.0 (Harness-First)
# =============================================================================
# [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
# =============================================================================

name: cc-devflow
version: "6.0.0"
description: CC-DevFlow Harness-First workflow schema

# =============================================================================
# 工件定义 (Artifacts)
# =============================================================================
# 主链：init -> spec -> dev -> verify -> release
# 产物最小集：context-package / task-manifest / report-card / release-note

artifacts:
  - id: context_package
    generates: devflow/requirements/{REQ}/context-package.md
    requires: []
    skill: flow-init
    instruction: |
      初始化需求并生成上下文包。

  - id: harness_state
    generates: devflow/requirements/{REQ}/harness-state.json
    requires: [context_package]
    skill: flow-init
    instruction: |
      记录 requirement 生命周期状态。

  - id: task_manifest
    generates: devflow/requirements/{REQ}/task-manifest.json
    requires: [context_package]
    skill: flow-spec
    instruction: |
      生成依赖可执行的任务清单。

  - id: runtime_events
    generates: .harness/runtime/{REQ}/**
    requires: [task_manifest]
    skill: flow-dev
    glob: true
    optional: true
    instruction: |
      执行任务并写入 checkpoint/events。

  - id: report_card
    generates: devflow/requirements/{REQ}/report-card.json
    requires: [task_manifest]
    skill: flow-verify
    instruction: |
      执行 quick/strict 质量门禁并产出报告卡。

  - id: release_note
    generates: devflow/requirements/{REQ}/RELEASE_NOTE.md
    requires: [report_card]
    skill: flow-release
    optional: true
    instruction: |
      发布通过后生成发布说明。

  - id: bug_analysis
    generates: devflow/bugs/{BUG}/ANALYSIS.md
    requires: []
    skill: flow-fix
    optional: true
    instruction: |
      分析 Bug 根因并沉淀修复输入。

  - id: bug_plan
    generates: devflow/bugs/{BUG}/PLAN.md
    requires: [bug_analysis]
    skill: flow-fix
    optional: true
    instruction: |
      生成 Bug 修复计划。

# =============================================================================
# 状态检测配置
# =============================================================================
detection:
  method: file_existence
  fallback: harness-state.json
  glob_options:
    ignore:
      - "**/.DS_Store"
      - "**/*.bak"
      - "**/node_modules/**"

# =============================================================================
# Skill 分类定义
# =============================================================================
# 仅登记仓库内实际存在的 skill 目录

skills:
  workflow:
    - id: flow-init
      path: workflow/flow-init
      description: 主链初始化 (context-package + harness-state)
    - id: flow-spec
      path: workflow/flow-spec
      description: 主链规格阶段 (task-manifest)
    - id: flow-dev
      path: workflow/flow-dev
      description: 主链开发执行 (dispatch/resume)
    - id: flow-verify
      path: workflow/flow-verify
      description: 主链质量门禁 (report-card)
    - id: flow-release
      path: workflow/flow-release
      description: 主链发布收尾 (release/janitor)
    - id: flow-quality
      path: workflow/flow-quality
      description: 旧质量流程 (deprecated)
    - id: flow-fix
      path: workflow/flow-fix
      description: Bug 修复

  domain:
    - id: tdd
      path: domain/tdd
      description: TDD Iron Law 执行
    - id: debugging
      path: domain/debugging
      description: 系统化调试
    - id: brainstorming
      path: domain/brainstorming
      description: 需求头脑风暴
    - id: attention-refresh
      path: domain/attention-refresh
      description: 注意力刷新协议
    - id: verification
      path: domain/verification
      description: 完成前验证
    - id: receiving-review
      path: domain/receiving-review
      description: 处理代码审查反馈
    - id: finishing-branch
      path: domain/finishing-branch
      description: 分支完成决策

  guardrail:
    - id: constitution-guardian
      path: guardrail/constitution-guardian
      description: Constitution 合规检查
    - id: tdd-enforcer
      path: guardrail/tdd-enforcer
      description: TDD 顺序强制执行

  utility:
    - id: npm-release
      path: utility/npm-release
      description: NPM 包发布
    - id: fractal-docs
      path: utility/fractal-docs
      description: 分形文档生成
    - id: journey-checker
      path: utility/journey-checker
      description: 跨需求一致性检查
    - id: skill-creator
      path: utility/skill-creator
      description: Skill 创建向导
    - id: file-standards
      path: utility/file-standards
      description: 文件命名规范
    - id: constitution-quick-ref
      path: utility/constitution-quick-ref
      description: Constitution 快速参考

# =============================================================================
# 上下文注入配置
# =============================================================================
context:
  global:
    - file: .claude/rules/project-constitution.md
      reason: Quality rules and constraints

  defaults:
    workflow:
      - file: devflow/requirements/{REQ}/context-package.md
        reason: Execution context package
        optional: true
      - file: devflow/requirements/{REQ}/task-manifest.json
        reason: Executable task graph
        optional: true
    domain:
      - file: devflow/requirements/{REQ}/task-manifest.json
        reason: Current task context
        optional: true

# =============================================================================
# 废弃命令/技能映射
# =============================================================================
deprecated:
  - id: flow-new
    replacement: flow-init
    message: "Use /flow:init -> /flow:spec -> /flow:dev -> /flow:verify -> /flow:release"
  - id: flow-clarify
    replacement: flow-spec
    message: "Clarification stage removed from default chain"
  - id: flow-checklist
    replacement: flow-verify
    message: "Checklist stage merged into verification gates"
  - id: flow-quality
    replacement: flow-verify
    message: "Use /flow:verify for quick/strict gates"
  - id: flow-prd
    replacement: flow-spec
    message: "Use /flow:spec instead"
  - id: flow-tech
    replacement: flow-spec
    message: "Use /flow:spec instead"
  - id: flow-ui
    replacement: flow-spec
    message: "Use /flow:spec instead"
  - id: flow-epic
    replacement: flow-spec
    message: "Use /flow:spec instead"
